<div class="col-md-8 col-md-offset-2">
    <h1>Link Shortener</h1>
    <form role="form" class="form-horizontal" ng-controller="LinkShortenerCtrl" ng-submit="submit()">
        <fieldset>
            <label for="origURL" class="control-label">URL to shorten:</label>
            <div class="input-group">
                <input id="origURL" type="text" class="form-control" ng-model="linkURL">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">Shorten Link</button>
                </span>
            </div>
            <div class="help-block">Enter a URL to generate shortened links</div>
            <div ng-show="shortlinks.length" class="well row animate-show">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3" ng-repeat="link in shortlinks" ng-hide="$index == 0">
                    <input name="{{ link.id }}_enabled" ng-model="link.enabled" type="checkbox">
                    <label for="{{ link.id }}_enabled">{{ link.service }}</label>
                </div>
            </div>
            <div ng-show="displayDetails()" class="row col-md-12 animate-show">
                <div class="input-group">
                    <label for="description" class="control-label">Description:</label>
                    <textarea id="description" class="form-control" ng-model="linkDesc"></textarea>
                </div>
            </div>
        </fieldset>
        <hr>
        <fieldset ng-show="displayShortlinks()" class="row col-md-12 animate-show">
            <legend>Shortened Links</legend>
            <div ng-repeat="link in shortlinks" class="row col-md-12" ng-class-odd="odd" ng-show="link.shorturl || link.authlink">
                <label for="shortlink-{{ link.id }}" class="control-label col-md-3">{{ link.service }}</label>
                <p id="shortlink-{{ link.id }}" class="form-control-static col-md-7">
                    <a ng-show="link.success" href="{{ link.shorturl }}">{{ link.shorturl }}</a>
                    <span ng-hide="link.success">{{ link.shorturl }}</span>
                </p>
                <p id="authlink-{{ link.id }}" class="form-control-static col-md-2" ng-show="link.authlink">
                    <a href="{{ link.authlink }}" class="btn btn-default">Login</a>
                </p>
            </div>
        </fieldset>
    </form>
</div>
