<div class="col-md-8 col-md-offset-2">
    <form role="form" class="form-vertical" ng-controller="LinkShortenerCtrl" ng-submit="submit()">
        <fieldset>
            <legend>Link Shortener</legend>
            <div class="form-group">
                <label for="origURL" class="control-label">URL to shorten:</label> <input id="origURL" type="text" class="form-control input-lg" ng-model="linkURL"> <span class="help-block">Enter a URL to generate shortened links</span>
            </div>
            <button type="submit" class="btn btn-default btn-block">Shorten Link</button>
        </fieldset>
        <hr>
        <fieldset>
            <legend>Shortened Links</legend>
            <div class="form-group" ng-repeat="link in shortlinks">
                <label for="shortlink-{{ link.id }}" class="control-label">{{ link.service }}</label>
                <p id="shortlink-{{ link.id }}" class="form-control-static">
                    <a href="{{ link.shorturl }}">{{ link.shorturl }}</a>
                </p>
            </div>
        </fieldset>
    </form>
</div>
